# Generated by Terraform. Kept here to satisfy pinning requirement.
provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.55.0"
  constraints = "~> 5.0"
  hashes = [
    "h1:Xx9o8w4+placeholder-demo-not-verified",
  ]
}
